TRAIN:
  ENABLE: True
  DATASET: virat
  BATCH_SIZE: 3
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: SLOWFAST_32x2_R101_50_50_v2.1.pkl #SLOWFAST_8x8_R50.pkl # please download from the model zoo.
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 360]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3] # For slow and fast pathways
  MULTI_LABEL: True
  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
DETECTION:
  ENABLE: True
  ALIGNED: False
VIRAT:
  ANNOTATION_DIR: /data/virat-v2/annotations/
  LABEL_MAP_FILE: virat_label_map_file.pbtxt
  GROUNDTRUTH_FILE: dev_annotations.csv
  FRAME_LIST_DIR: /data/virat-v2/frame_lists
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  # SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]] # Matches paper
  # SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]] # Matches paper
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101 #50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  # LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  # GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  # INSTANTIATION: dot_product
  LOCATION: [[[], []], [[], []], [[6, 13, 20], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1
SOLVER:
  BASE_LR: 0.0375
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 41, 49]
  MAX_EPOCH: 57
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 4.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 12
  ARCH: slowfast
  LOSS_FUNC: bce_logit #  nn.BCEWithLogitsLoss
  # HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: virat
  BATCH_SIZE: 1
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: True
TENSORBOARD:
  ENABLE: True
  CONFUSION_MATRIX:
    ENABLE: True
  # MODEL_VIS:
  #   ENABLE: True
  #   MODEL_WEIGHTS: True
  #   ACTIVATIONS: True
  #   INPUT_VIDEO: True
    # LAYER_LIST: True
    # GRAD_CAM:
    #   ENABLE: True
    #   LAYER_LIST: # List of CNN layers to use for Grad-CAM visualization method.
    #               # The number of layer must be equal to the number of pathway(s).